<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function ($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'tddworkshop\\calculator' => '/Calculator.php',
                'tddworkshop\\tictactoe\\board' => '/tictactoe/Board.php',
                'tddworkshop\\tictactoe\\field' => '/tictactoe/Field.php',
                'tddworkshop\\tictactoe\\fieldisfilledexception' => '/tictactoe/FieldIsFilledException.php',
                'tddworkshop\\tictactoe\\playerplacesbeforeexception' => '/tictactoe/PlayerPlacesBeforeException.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
